version: '3'
services:
  api:
    build: ./docker/golang
    container_name: golnag_api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/go/src/pntnt/backend
    stdin_open: true
    tty: true
    command: /bin/bash
    
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_PASSWORD: pass
      
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d